const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+' ₡';const fmtPct=n=>`${n>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const DEMO={price:125.40,prev:125.40,shares:0,cash:10000,history:[118,119,117,121,120,122,124,123,125,124,126,125.4],orders:[],news:[]};let state=JSON.parse(localStorage.getItem('kspMarketState')||'null')||structuredClone(DEMO);let side='buy',authMode='signup',online=false,supabaseClient=null,session=null;
function save(){localStorage.setItem('kspMarketState',JSON.stringify(state))}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function chart(){const c=$('chart'),x=c.getContext('2d'),w=c.width,h=c.height,v=state.history,min=Math.min(...v)-2,max=Math.max(...v)+2;x.clearRect(0,0,w,h);x.strokeStyle='#58e0a2';x.lineWidth=3;x.beginPath();v.forEach((n,i)=>{const px=10+i*(w-20)/Math.max(v.length-1,1),py=h-12-(n-min)/(max-min||1)*(h-24);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();}
function update(){const change=((state.price-state.prev)/state.prev)*100;$('stockPrice').textContent=money(state.price);$('modalPrice').textContent=money(state.price);$('stockChange').textContent=fmtPct(change);$('stockChange').className=change>=0?'up':'down';$('bid').textContent=money(state.price);$('ask').textContent=money(state.price*1.001);$('portfolioCash').textContent=money(state.cash);$('portfolioShares').textContent=state.shares;$('portfolioTotal').textContent=money(state.cash+state.shares*state.price);$('portfolioPnL').textContent=fmtPct(change);$('portfolioMode').textContent=online?'Online':'Demo';$('userCash').textContent=(session?.user?.email||'Demo')+' · '+money(state.cash);$('tradeTotal').textContent=money((Number($('quantity').value)||0)*state.price);$('volume').textContent=state.orders.reduce((a,o)=>a+Number(o.quantity),0);$('stockVolume').textContent=$('volume').textContent;$('indexValue').textContent=money(1000*(state.price/125.4));$('indexChange').textContent=fmtPct(change);chart();renderHoldings();renderOrders();renderFeed();}
function renderHoldings(){$('holdingsTable').innerHTML=state.shares?`<table class="holdings-table"><thead><tr><th>Empresa</th><th>Acciones</th><th>Precio</th><th>Valor</th><th></th></tr></thead><tbody><tr><td><b>KD</b> · Kerbin Dynamics</td><td>${state.shares}</td><td>${money(state.price)}</td><td>${money(state.shares*state.price)}</td><td><button class="sell" onclick="openTrade('sell')">Vender</button></td></tr></tbody></table>`:'<div class="empty">No tienes posiciones todavía. Compra KD para empezar.</div>'}
function renderOrders(){$('ordersTable').innerHTML=state.orders.length?`<table class="holdings-table"><thead><tr><th>Fecha</th><th>Empresa</th><th>Tipo</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>${state.orders.slice().reverse().map(o=>`<tr><td>${new Date(o.date).toLocaleString('es-ES')}</td><td>KD</td><td class="${o.side==='buy'?'up':'down'}">${o.side==='buy'?'COMPRA':'VENTA'}</td><td>${o.quantity}</td><td>${money(o.price)}</td><td>${money(o.quantity*o.price)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Todavía no hay operaciones.</div>'}
function renderFeed(){$('tradeFeed').innerHTML=state.orders.length?state.orders.slice(-6).reverse().map(o=>`<div class="${o.side}line"><b>${o.side==='buy'?'COMPRA':'VENTA'}</b> · ${o.quantity} KD · ${money(o.price)}</div>`).join(''):'<p class="muted">Esperando operaciones…</p>'}
function renderNews(news=[]){$('newsList').innerHTML=news.length?news.map(n=>`<article class="news"><span class="badge">${n.source||'DISCORD'}</span><h3>${esc(n.title||n.text)}</h3><p>${esc(n.body||'')}</p></article>`).join(''):'<article class="news"><span class="badge">DISCORD</span><h3>Esperando la primera noticia del día</h3><p>Cuando el bot publique noticias, aparecerán aquí.</p></article>'}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
async function loadMarket(){try{const r=await fetch('./market-data.json?'+Date.now());const d=await r.json();const c=d.companies?.[0];if(c){state.prev=state.price;state.price=Number(c.price);state.history=[...(c.history||state.history),state.price].slice(-30);$('companyCount').textContent=d.companies.length;$('lastUpdate').textContent=d.updatedAt?'Actualizado '+new Date(d.updatedAt).toLocaleString('es-ES'):'Demo';$('marketReason').textContent=d.news?.[0]?.text||'El precio responde a las operaciones y al sentimiento del mercado.';$('signalBadge').textContent=c.signal||'NEUTRAL';$('signalText').textContent=d.marketSentiment>0.15?'Presión compradora':d.marketSentiment<-0.15?'Presión vendedora':'Mercado equilibrado';renderNews(d.news||[]);save();update()}}catch(e){$('lastUpdate').textContent='Modo demo'}}
async function initOnline(){const cfg=window.KSP_SUPABASE||{};if(!cfg.url||!cfg.anonKey||!window.supabase)return;supabaseClient=window.supabase.createClient(cfg.url,cfg.anonKey);const {data}=await supabaseClient.auth.getSession();session=data.session;online=!!session;if(session)await loadProfile();supabaseClient.auth.onAuthStateChange(async(_e,s)=>{session=s;online=!!s;if(s)await loadProfile();else{online=false;update()}});update()}
async function loadProfile(){if(!session)return;const {data,error}=await supabaseClient.from('profiles').select('*').eq('id',session.user.id).single();if(!error&&data){state.cash=Number(data.virtual_cash);$('userCash').textContent=(data.username||session.user.email)+' · '+money(state.cash)}const {data:h}=await supabaseClient.from('holdings').select('shares').eq('user_id',session.user.id).eq('company_id',await companyId());state.shares=Number(h?.[0]?.shares||0);const {data:o}=await supabaseClient.from('orders').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(50);state.orders=(o||[]).map(x=>({side:x.side,quantity:x.quantity,price:x.price,date:x.created_at}));update()}
async function companyId(){const {data}=await supabaseClient.from('companies').select('id').eq('ticker','KD').single();return data?.id}
async function auth(){const email=$('email').value,password=$('password').value,username=$('username').value;if(!online&&(!supabaseClient)){toast('El backend online aún no está configurado.');return}if(authMode==='signup'){const {data,error}=await supabaseClient.auth.signUp({email,password});if(error)return toast(error.message);if(data.user){await supabaseClient.from('profiles').upsert({id:data.user.id,username:username||email.split('@')[0],display_name:username||email.split('@')[0]});toast('Cuenta creada. Revisa tu email si se solicita confirmación.')}}else{const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return toast(error.message);toast('Sesión iniciada')}closeAuth()}
function openAuth(login=false){authMode=login?'login':'signup';$('authTitle').textContent=login?'Iniciar sesión':'Crear cuenta';$('authSubmit').textContent=login?'Entrar':'Crear cuenta';$('usernameWrap').style.display=login?'none':'block';$('toggleAuth').textContent=login?'Crear una cuenta →':'Ya tengo cuenta → Iniciar sesión';$('authModal').classList.remove('hidden')}
function closeAuth(){$('authModal').classList.add('hidden')}
window.openTrade=(s='buy')=>{side=s;$('tradeTitle').textContent=s==='buy'?'Comprar KD':'Vender KD';$('tradeEyebrow').textContent=s==='buy'?'ORDEN DE COMPRA':'ORDEN DE VENTA';$('confirmTrade').textContent=s==='buy'?'Confirmar compra':'Confirmar venta';$('quantity').value=1;$('tradeModal').classList.remove('hidden');update()};
async function trade(){const q=Math.floor(Number($('quantity').value));if(q<1)return;if(online&&supabaseClient&&session){const cid=await companyId();const {data,error}=await supabaseClient.rpc('place_market_order',{p_company:cid,p_side:side,p_quantity:q});if(error)return toast(error.message);state.prev=state.price;state.price=Number(data.new_price);await loadProfile();toast(`${side==='buy'?'Compra':'Venta'} ejecutada. Precio ${money(state.price)}`)}else{if(side==='buy'){if(q*state.price>state.cash)return toast('Saldo insuficiente');state.cash-=q*state.price;state.shares+=q;state.price=Number((state.price*(1+Math.min(.05,q/10000))).toFixed(2))}else{if(state.shares<q)return toast('No tienes suficientes acciones');state.shares-=q;state.cash+=q*state.price;state.price=Number(Math.max(.01,state.price*(1-Math.min(.05,q/10000))).toFixed(2))}state.orders.push({side,quantity:q,price:side==='buy'?state.price/(1+Math.min(.05,q/10000)):state.price,date:new Date().toISOString()});state.history.push(state.price);state.history=state.history.slice(-30);save();update();toast(`${side==='buy'?'Compra':'Venta'} ejecutada · el precio se ha movido`)}$('tradeModal').classList.add('hidden');update()}
$('accountBtn').onclick=()=>session?supabaseClient.auth.signOut():openAuth(false);$('closeModal').onclick=closeAuth;$('closeTrade').onclick=()=>$('tradeModal').classList.add('hidden');$('authForm').onsubmit=e=>{e.preventDefault();auth()};$('toggleAuth').onclick=()=>openAuth(authMode==='signup');$('confirmTrade').onclick=trade;$('quantity').oninput=update;$('buyBtn').onclick=()=>openTrade('buy');$('sellBtn').onclick=()=>openTrade('sell');$('detailsBtn').onclick=()=>toast('KD · Kerbin Dynamics · Aeroespacial · Empresa ficticia');$('portfolioBuy').onclick=()=>openTrade('buy');
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(b.dataset.view+'View').classList.add('active')});
update();loadMarket();initOnline();