const DEMO={price:125.40,shares:0,cash:10000,history:[118,119,117,121,120,122,124,123,125,124,126,125.4]};
let state=JSON.parse(localStorage.getItem('kspExchangeState')||'null')||structuredClone(DEMO);
const $=id=>document.getElementById(id); const money=n=>new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' ₡';
async function loadMarket(){try{const r=await fetch('./market-data.json?'+Date.now());const d=await r.json();const c=d.companies?.[0];if(c){state.price=c.price;state.history.push(c.price);if(state.history.length>24)state.history.shift();$('stockChange').textContent=`${c.dailyChange>=0?'+':''}${c.dailyChange.toFixed(2)}%`;$('stockChange').className=c.dailyChange>=0?'positive':'negative';$('signalBadge').textContent=c.signal;$('marketReason').textContent=d.news?.[0]?.text||'Sin noticias publicadas hoy.';$('sentiment').textContent=d.marketSentiment>0.15?'Positivo':d.marketSentiment<-0.15?'Negativo':'Neutral';$('companyCount').textContent=d.companies.length;$('lastUpdate').textContent=d.updatedAt?'Última actualización: '+new Date(d.updatedAt).toLocaleString('es-ES'):'Esperando actualización';renderNews(d.news||[]);save(false)}}catch(e){$('marketStatus').textContent='Modo demo';}}
function save(refresh=true){localStorage.setItem('kspExchangeState',JSON.stringify(state));if(refresh)updateUI()}
function updateUI(){ $('stockPrice').textContent=money(state.price); $('modalPrice').textContent=money(state.price); $('balanceLabel').textContent=localStorage.getItem('kspUser')?`${localStorage.getItem('kspUser')} · ${money(state.cash)}`:`Demo · ${money(state.cash)}`; $('portfolioCash').textContent=money(state.cash); $('shares').textContent=state.shares; $('positionValue').textContent=money(state.shares*state.price); $('portfolioTotal').textContent=money(state.cash+state.shares*state.price); $('tradeTotal').textContent=money((Number($('quantity').value)||0)*state.price); drawChart(); }
function drawChart(){const c=$('chart'),x=c.getContext('2d'),w=c.width,h=c.height,p=14,vals=state.history,min=Math.min(...vals)-2,max=Math.max(...vals)+2;x.clearRect(0,0,w,h);x.beginPath();vals.forEach((v,i)=>{const px=p+i*(w-p*2)/(vals.length-1),py=h-p-(v-min)/(max-min)*(h-p*2);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#62d7a3';x.lineWidth=3;x.stroke();}
function renderNews(news){$('newsList').innerHTML=news.length?news.map(n=>`<article class="news-item"><span class="pill">DISCORD</span><h3>${escapeHtml(n.text)}</h3><small>${escapeHtml(n.author||'Discord')} · ${n.date?new Date(n.date).toLocaleString('es-ES'):''}</small></article>`).join(''):'<p class="muted">No hay noticias todavía.</p>'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function openAuth(login=false){$('authModal').classList.remove('hidden');if(login){$('authContent').innerHTML=`<p class="eyebrow">KSP MARKET T/E</p><h2>Iniciar sesión</h2><p class="muted">Demo local.</p><form id="loginForm"><label>Nombre de usuario<input id="loginUser" required></label><label>Contraseña<input id="loginPass" type="password" required></label><button class="buy full">Entrar</button></form><p class="switch">¿No tienes cuenta? <button id="showRegister" type="button">Regístrate</button></p>`;$('loginForm').onsubmit=e=>{e.preventDefault();if($('loginUser').value===localStorage.getItem('kspUser')&&$('loginPass').value===localStorage.getItem('kspPass')){$('authModal').classList.add('hidden');toast('Sesión iniciada');updateUI()}else toast('Usuario o contraseña incorrectos')};$('showRegister').onclick=()=>openAuth(false)}}
$('accountBtn').onclick=()=>localStorage.getItem('kspUser')?(localStorage.removeItem('kspUser'),toast('Sesión cerrada'),updateUI()):openAuth(false);$('closeModal').onclick=()=>$('authModal').classList.add('hidden');$('closeTrade').onclick=()=>$('tradeModal').classList.add('hidden');$('showLogin').onclick=()=>openAuth(true);
$('registerForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('kspUser',$('username').value);localStorage.setItem('kspPass',$('password').value);$('authModal').classList.add('hidden');toast('Cuenta creada. ¡Bienvenido a KSP Market T/E!');updateUI()};function openTrade(){$('tradeModal').classList.remove('hidden');$('quantity').value=1;updateUI()};$('buyBtn').onclick=openTrade;$('portfolioBuy').onclick=openTrade;$('quantity').oninput=updateUI;
$('confirmBuy').onclick=()=>{const q=Math.floor(Number($('quantity').value));if(q<1)return;if(q*state.price>state.cash){toast('Saldo insuficiente');return}state.cash-=q*state.price;state.shares+=q;$('tradeModal').classList.add('hidden');save();toast(`Compra realizada: ${q} acción${q>1?'es':''} de KD`)};$('sellBtn').onclick=()=>{if(state.shares<1){toast('No tienes acciones para vender');return}state.shares--;state.cash+=state.price;save();toast('Has vendido 1 acción de KD')};$('detailsBtn').onclick=()=>toast('KD · Kerbin Dynamics · Aeroespacial · Empresa ficticia');
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(b.dataset.view+'View').classList.add('active')});
updateUI();loadMarket();
