(function(){
const $=id=>document.getElementById(id);let busy=false;
const show=m=>{const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__kspToast);window.__kspToast=setTimeout(()=>e.classList.remove('show'),3200)};
const withTimeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(Error(message)),ms))]);
async function refresh(){try{if(!supabaseClient)return;const {data,error}=await withTimeout(supabaseClient.from('companies').select('price,previous_close').eq('ticker','KD').maybeSingle(),5000,'No se pudo actualizar la cotización.');if(error||!data)return;state.prev=Number(data.previous_close||state.price);state.price=Number(data.price);update()}catch(e){console.warn('KSP market refresh:',e.message)}}
async function syncAfterOrder(){try{await withTimeout(loadProfile(),5000,'perfil')}catch(e){console.warn('KSP profile sync:',e.message)}try{await withTimeout(loadHistory(),5000,'historial')}catch(e){console.warn('KSP history sync:',e.message)}try{update()}catch(e){console.warn('KSP UI sync:',e.message)}}
async function safeTrade(){if(busy)return;if(!session||!supabaseClient)return show('Inicia sesión para operar online');const q=Math.floor(Number($('quantity').value));if(!Number.isSafeInteger(q)||q<1)return show('Cantidad no válida');busy=true;const b=$('confirmTrade'),old=b.textContent;b.disabled=true;b.textContent='Ejecutando…';try{const cid=await withTimeout(companyId(),5000,'Tiempo agotado buscando KD.');if(!cid)throw Error('No se encontró KD en la base de datos.');const result=await withTimeout(supabaseClient.rpc('place_market_order',{p_company:cid,p_side:side,p_quantity:q}),12000,'La orden no respondió a tiempo. No repitas la orden todavía: revisa Operaciones, porque puede haberse ejecutado.');const {data,error}=result;if(error)throw Error(error.message);const r=Array.isArray(data)?data[0]:data;if(!r||r.new_price==null)throw Error('Supabase no devolvió una cotización válida.');const executedSide=side;state.prev=Number(state.price);state.price=Number(r.new_price);if(executedSide==='buy'){state.shares+=q;state.cash=Math.max(0,state.cash-Number(r.price)*q)}else{state.shares=Math.max(0,state.shares-q);state.cash+=Number(r.price)*q}state.orders.unshift({side:executedSide,quantity:q,price:Number(r.price),date:new Date().toISOString()});save();$('tradeModal').classList.add('hidden');update();show((executedSide==='buy'?'Compra':'Venta')+' ejecutada · '+q+' KD · '+money(r.price));busy=false;b.disabled=false;b.textContent=old;void syncAfterOrder();return}catch(e){console.error('KSP order error',e);show('No se pudo ejecutar la orden: '+e.message)}finally{busy=false;b.disabled=false;b.textContent=old;update()}}
async function forceSyncAuth(){if(!window.supabase||!window.KSP_SUPABASE)return;try{if(!supabaseClient)supabaseClient=window.supabase.createClient(window.KSP_SUPABASE.url,window.KSP_SUPABASE.anonKey);const {data,error}=await withTimeout(supabaseClient.auth.getSession(),6000,'No se pudo comprobar la sesión.');if(error)throw error;session=data.session||null;online=!!session;if(session){try{await withTimeout(loadProfile(),6000,'perfil')}catch(e){console.warn('KSP auth profile:',e.message);profileName=session.user.user_metadata?.username||session.user.email?.split('@')[0]||'Usuario'}setAccountUI();update();}else{profileName=null;setAccountUI();update()}}catch(e){console.warn('KSP auth sync:',e.message)}}
function install(){const b=$('confirmTrade');if(b)b.onclick=safeTrade;void refresh();void forceSyncAuth();if(supabaseClient){supabaseClient.auth.onAuthStateChange((event,s)=>{session=s||null;online=!!session;if(session){profileName=session.user.user_metadata?.username||session.user.email?.split('@')[0]||'Usuario';setAccountUI();update();setTimeout(()=>void forceSyncAuth(),0)}else{profileName=null;setAccountUI();update()}});supabaseClient.channel('ksp-defensive-live-v3').on('postgres_changes',{event:'UPDATE',schema:'public',table:'companies',filter:'ticker=eq.KD'},p=>{if(p.new&&!busy){state.prev=state.price;state.price=Number(p.new.price);update()}}).subscribe()}}
setTimeout(install,1000);
})();